- name: pilot.desktop.http.port
  recommendExpression: 8086
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionUserName
  recommendExpression: pilotuser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionPassword
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: PASSWORD

- name: pilot.container.limits.memory
  recommendExpression: 4
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [PILOT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: pilot.container.limits.cpu
  recommendExpression: 1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [PILOT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: pilot.container.requests.memory
  recommendExpression: 0
  defaultValue: null
  valueType: GB
  scope: !<RoleTypes>
    roleTypes: [PILOT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: pilot.container.requests.cpu
  recommendExpression: 0
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<RoleTypes>
    roleTypes: [PILOT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: pilot.memory.ratio
  recommendExpression: 0.9
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [PILOT_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE
