- name: hive.exec.scratchdir
  recommendExpression: |
    <#function hdfsUri path>
      <#local hdfs=dependencies['HDFS']>
      <#if hdfs['nameservices']?? && hdfs['nameservices']?size gt 0>
        <#local hostPort=hdfs['nameservices'][0]>
      <#else>
        <#local host=hdfs['roles']['HDFS_NAMENODE'][0]['hostname']>
        <#if hdfs['namenode.rpc-port']??>
          <#local port=hdfs['namenode.rpc-port']>
        </#if>
        <#if hdfs[host]?? && hdfs[host]['namenode.rpc-port']??>
          <#local port=hdfs[host]['namenode.rpc-port']>
        </#if>
        <#local hostPort=host + ':' + port>
      </#if>
      <#return 'hdfs://' + hostPort + path>
    </#function>
    ${hdfsUri("/" + service['sid'] + '/tmp/hive')}
  defaultValue: "/tmp/hive-${user.name}"
  valueType: URI
  scope: !<ServiceLevel> {}
  onDeps: ['HDFS']
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.metastore.warehouse.dir
  recommendExpression: |
    <#function hdfsUri path>
      <#local hdfs=dependencies['HDFS']>
      <#if hdfs['nameservices']?? && hdfs['nameservices']?size gt 0>
        <#local hostPort=hdfs['nameservices'][0]>
      <#else>
        <#local host=hdfs['roles']['HDFS_NAMENODE'][0]['hostname']>
        <#if hdfs['namenode.rpc-port']??>
          <#local port=hdfs['namenode.rpc-port']>
        </#if>
        <#if hdfs[host]?? && hdfs[host]['namenode.rpc-port']??>
          <#local port=hdfs[host]['namenode.rpc-port']>
        </#if>
        <#local hostPort=host + ':' + port>
      </#if>
      <#return 'hdfs://' + hostPort + path>
    </#function>
    ${hdfsUri("/" + service['sid'] + '/user/hive/warehouse')}
  defaultValue: "/user/hive/warehouse"
  valueType: URI
  scope: !<RoleTypes>
    roleTypes: [INCEPTOR_METASTORE]
  onDeps: ['HDFS']
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.metastore.execute.setugi
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.hwi.war.file
  recommendExpression: lib/hive-hwi-0.8.1.war
  defaultValue: null
  valueType: ABSOLUTE_PATH
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: plsql.compile.dml.check.semantic
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionPassword
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: PASSWORD

- name: hive.server2.session.check.interval
  recommendExpression: 60000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.users.in.admin.role
  recommendExpression: hive,hue
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: mapreduce.framework.name
  recommendExpression: yarn
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hbase.client.scanner.caching
  recommendExpression: 500
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: datanucleus.autoStartMechanism
  recommendExpression: SchemaTable
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.input.format
  recommendExpression: org.apache.hadoop.hive.ql.io.HiveInputFormat
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.aux.jars.path
  recommendExpression: file:///usr/lib/hive/lib/hive-hbase-handler.jar,file:///usr/lib/hbase/hbase-bson.jar,file:///usr/lib/hbase/hbase-client.jar,file:///usr/lib/hbase/hbase-common.jar,file:///usr/lib/hbase/hbase-examples.jar,file:///usr/lib/hbase/hbase-hadoop2-compat.jar,file:///usr/lib/hbase/hbase-hadoop-compat.jar,file:///usr/lib/hbase/hbase-hyperbase.jar,file:///usr/lib/hbase/hbase-it.jar,file:///usr/lib/hbase/hbase-prefix-tree.jar,file:///usr/lib/hbase/hbase-protocol.jar,file:///usr/lib/hbase/hbase-server.jar,file:///usr/lib/hbase/hbase-shell.jar,file:///usr/lib/hbase/hbase-testing-util.jar,file:///usr/lib/hbase/hbase-thrift.jar,file:///usr/lib/hbase/chronos-client.jar,file:///usr/lib/hbase/chronos-server.jar,file:///usr/lib/hbase/transaction-client.jar,file:///usr/lib/hbase/transaction-coprocessor.jar,file:///usr/lib/zookeeper/zookeeper.jar,file:///usr/lib/hbase/lib/protobuf-java-2.5.0.jar,file:///usr/lib/hive/lib/kryo-2.21.jar
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.server2.idle.session.timeout
  recommendExpression: 14400000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: datanucleus.fixedDatastore
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionDriverName
  recommendExpression: com.mysql.jdbc.Driver
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionUserName
  recommendExpression: hiveuser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.exec.dynamic.partition
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hbase.zookeeper.property.clientPort
  recommendExpression: 2181
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.exec.compress.output
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.server2.authentication
  recommendExpression: NONE
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.server2.idle.operation.timeout
  recommendExpression: 28800000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: datanucleus.autoCreateSchema
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.exec.compress.intermediate
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.server2.logging.operation.enabled
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.server2.enabled
  recommendExpression: true
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.server2.authentication
  recommendExpression: LDAP
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: ngmr.fastdisk.dir
  recommendExpression: /mnt/ramdisk/ngmr
  defaultValue: null
  valueType: ABSOLUTE_PATH
  scope: !<RoleTypes>
    roleTypes: [INCEPTOR_SERVER, INCEPTOR_EXECUTOR]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ngmr.localdir
  recommendExpression: |
    <#function localDir suffix>
      <#if rcmdMounts?size == 0>
        <#return suffix>
      <#else>
        <#local dirs = []>
        <#list rcmdMounts?sort as mnt>
         <#local dirs = dirs + [mnt + suffix]>
        </#list>
        <#return dirs?join(",")>
      </#if>
    </#function>
    ${localDir("/hadoop/ngmr/" + service['sid'])}
  isNodeSpecific: true
  defaultValue: null
  valueType: ABSOLUTE_PATH
  scope: !<RoleTypes>
    roleTypes: [INCEPTOR_SERVER, INCEPTOR_EXECUTOR]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ngmr.fastdisk.size
  recommendExpression: 0.5
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [INCEPTOR_SERVER, INCEPTOR_EXECUTOR]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ngmr.cache.size
  recommendExpression: 0.5
  defaultValue: null
  valueType: FLOAT
  scope: !<RoleTypes>
    roleTypes: [INCEPTOR_SERVER, INCEPTOR_EXECUTOR]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: ngmr.executors.perjob
  recommendExpression: 1
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.yarn.master.memory
  recommendExpression: 512
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.yarn.executor.memory
  recommendExpression: 1569
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.yarn.executor.cores
  recommendExpression: 3
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.yarn.number.executors
  recommendExpression: -1
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.yarn.number.workers
  recommendExpression: -1
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.yarn.scheduler.mode
  recommendExpression: GreedyMode
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: spark.yarn.queue
  recommendExpression: default
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.ui.port
  recommendExpression: 4044
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [INCEPTOR_SERVER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: hive.memory
  recommendExpression: 8192
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: hive.server2.thrift.port
  recommendExpression: 10010
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [INCEPTOR_SERVER]
  onDeps: []
  groups: ["hive-site.xml"]
  visibility: READ_WRITE

- name: hive.metastore.port
  recommendExpression: 9083
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [INCEPTOR_METASTORE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mysql.port
  recommendExpression: 3306
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: hive.cores
  recommendExpression: 2
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: inceptor.ngmr.yarn
  recommendExpression: false
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: mysql.datadir
  recommendExpression: /hadoop/mysql
  defaultValue: null
  valueType: STRING
  scope: !<RoleTypes>
    roleTypes: [INCEPTOR_MYSQL]
  onDeps: []
  groups: []
  visibility: READ_WRITE
