---
name: YARN
version: 2.5.2-tdh50
global: false
namePrefix: YARN
friendlyName: "YARN"
dockerImage: "tos/yarn:rb465-final-tdh-5"
dependencies:
  - name: ZOOKEEPER
    minVersion: 3.4.5-tdh50
    maxVersion: 3.4.5-tdh50
    optional: false
  - name: HDFS
    minVersion: 2.5.2-tdh50
    maxVersion: 2.5.2-tdh50
    optional: false
user: yarn
roles:
- name: YARN_RESOURCEMANAGER
  friendlyName: "Resource Manager"
  labelPrefix: "hadoop-yarn-resourcemanager"
  category: MASTER
  env:
  - name: USE_EXTERNAL_CONFIG
    value: "true"
  - name: KRB_ENABLE
    value: 'false'
  - name: YARN_RESOURCEMANAGER_ADDRRESS
    value: ${service.roles.YARN_RESOURCEMANAGER[0]['hostname']}
  - name: HADOOP_CONF_DIR
    value: /etc/${service.sid}/conf
  - name: DATA_DIRS
    value: ${service['yarn.nodemanager.local-dirs']},${service['yarn.nodemanager.log-dirs']}
  mountPath:
  - mountPath: /etc/${service.sid}/conf
    hostPath: /etc/${service.sid}/conf
    name: yarn
  - mountPath: /var/log/${service.sid}
    hostPath: /var/log/${service.sid}
    name: log
  - mountPath: /var/run/hadoop-common
    hostPath: /root/docker/common
    name: socketdir
  - mountPath: ${service['yarn.nodemanager.local-dirs']}
    hostPath: ${service['yarn.nodemanager.local-dirs']}
    name: datadir1
  - mountPath: ${service['yarn.nodemanager.log-dirs']}
    hostPath: ${service['yarn.nodemanager.log-dirs']}
    name: datadir2
  - mountPath: /var/transwarp
    hostPath: /var/${service.sid}
    name: transwarp
  - mountPath: /etc/${dependencies.HDFS.sid}/conf
    hostPath: /etc/${dependencies.HDFS.sid}/conf
    name: hdfs
  summaryPolicy: SOME
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [1]}
  suggestion:
  - criteria: !<Range> {"min": 1}
  validation:
  - criteria: !<Range> {"min": 1}
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}/conf", "/var/lock/subsys/${service.sid}", "/var/log/${service.sid}", "/var/run/${service.sid}"]
        mode: "755"
  - type: Config
    directives:
    - directive: !<resource>
        templateType: Raw
        templatePath: "log4j.properties"
        targetPath: "/etc/${service.sid}/conf/log4j.properties"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "yarn-site.ftlx"
        targetPath: "/etc/${service.sid}/conf/yarn-site.xml"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "yarn-env.sh"
        targetPath: "/etc/${service.sid}/conf/yarn-env.sh"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "hadoop-env.sh"
        targetPath: "/etc/${service.sid}/conf/hadoop-env.sh"
        mode: "755"
    - directive: !<link>
        action: Link
        from: "/etc/${dependencies.HDFS.sid}/conf/hdfs-site.xml"
        to: "/etc/${service.sid}/conf/hdfs-site.xml"
    - directive: !<link>
        action: Link
        from: "/etc/${dependencies.HDFS.sid}/conf/core-site.xml"
        to: "/etc/${service.sid}/conf/core-site.xml"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-maptask.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-maptask.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-reducetask.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-reducetask.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-resourcemanager.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-resourcemanager.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "yarn.exclude"
        targetPath: "/etc/${service.sid}/conf/yarn.exclude"
        mode: "644"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "mapred-env.sh"
        targetPath: "/etc/${service.sid}/conf/mapred-env.sh"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "mapred-site.ftlx"
        targetPath: "/etc/${service.sid}/conf/mapred-site.xml"
        mode: "755"
    - directive: !<resource>
        templateType: Raw
        templatePath: "taskcontroller.cfg"
        targetPath: "/etc/${service.sid}/conf/taskcontroller.cfg"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "capacity-scheduler.ftlx"
        targetPath: "/etc/${service.sid}/conf/capacity-scheduler.xml"
        mode: "755"
- name: YARN_NODEMANAGER
  friendlyName: "Node Manager"
  labelPrefix: "hadoop-yarn-nodemanager"
  category: SLAVE
  env:
  - name: USE_EXTERNAL_CONFIG
    value: "true"
  - name: KRB_ENABLE
    value: 'false'
  - name: NODEMANAGER_RESOURCE_MEMORY_MB
    value: ${service['yarn.nodemanager.resource.memory-mb']}
  - name: YARN_RESOURCEMANAGER_ADDRRESS
    value: ${service.roles.YARN_RESOURCEMANAGER[0]['hostname']}
  - name: NODEMANAGER_RESOURCE_CPU_VCORES
    value: ${service['yarn.nodemanager.resource.cpu-vcores']}
  - name: HADOOP_CONF_DIR
    value: /etc/${service.sid}/conf
  - name: DATA_DIRS
    value: ${service['yarn.nodemanager.local-dirs']},${service['yarn.nodemanager.log-dirs']}
  mountPath:
  - mountPath: /etc/${service.sid}/conf
    hostPath: /etc/${service.sid}/conf
    name: yarn
  - mountPath: /var/log/${service.sid}
    hostPath: /var/log/${service.sid}
    name: log
  - mountPath: /var/run/hadoop-common
    hostPath: /root/docker/common
    name: socketdir
  - mountPath: /var/transwarp
    hostPath: /var/${service.sid}
    name: transwarp
  - mountPath: ${service['yarn.nodemanager.local-dirs']}
    hostPath: ${service['yarn.nodemanager.local-dirs']}
    name: localdirs
  - mountPath: ${service['yarn.nodemanager.log-dirs']}
    hostPath: ${service['yarn.nodemanager.log-dirs']}
    name: logdirs
  - mountPath: /etc/${dependencies.HDFS.sid}/conf
    hostPath: /etc/${dependencies.HDFS.sid}/conf
    name: hdfs
  summaryPolicy: SOME
  autoAssign:
  - advice: !<EachNode> {}
  suggestion:
  - criteria: !<EachNode> {}
  validation:
  - criteria: !<EachNode> {}
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}/conf", "/var/lock/subsys/${service.sid}", "/var/log/${service.sid}", "/var/run/${service.sid}"]
        mode: "755"
  - type: Config
    directives:
    - directive: !<resource>
        templateType: Raw
        templatePath: "log4j.properties"
        targetPath: "/etc/${service.sid}/conf/log4j.properties"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "yarn-site.ftlx"
        targetPath: "/etc/${service.sid}/conf/yarn-site.xml"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "yarn-env.sh"
        targetPath: "/etc/${service.sid}/conf/yarn-env.sh"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "hadoop-env.sh"
        targetPath: "/etc/${service.sid}/conf/hadoop-env.sh"
        mode: "755"
    - directive: !<link>
        action: Link
        from: "/etc/${dependencies.HDFS.sid}/conf/hdfs-site.xml"
        to: "/etc/${service.sid}/conf/hdfs-site.xml"
    - directive: !<link>
        action: Link
        from: "/etc/${dependencies.HDFS.sid}/conf/core-site.xml"
        to: "/etc/${service.sid}/conf/core-site.xml"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-maptask.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-maptask.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-nodemanager.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-nodemanager.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-reducetask.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-reducetask.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "yarn.exclude"
        targetPath: "/etc/${service.sid}/conf/yarn.exclude"
        mode: "644"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "mapred-env.sh"
        targetPath: "/etc/${service.sid}/conf/mapred-env.sh"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "mapred-site.ftlx"
        targetPath: "/etc/${service.sid}/conf/mapred-site.xml"
        mode: "755"
    - directive: !<resource>
        templateType: Raw
        templatePath: "taskcontroller.cfg"
        targetPath: "/etc/${service.sid}/conf/taskcontroller.cfg"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "capacity-scheduler.ftlx"
        targetPath: "/etc/${service.sid}/conf/capacity-scheduler.xml"
        mode: "755"
- name: YARN_HISTORYSERVER
  friendlyName: "History Server"
  labelPrefix: "hadoop-yarn-historyserver"
  category: MASTER
  env:
  - name: USE_EXTERNAL_CONFIG
    value: "true"
  - name: KRB_ENABLE
    value: 'false'
  - name: HDFS_HA_NAMENODE_SERVICE
    value: |
      <#assign namenodes=[]>
      <#if dependencies.HDFS.nameservices?? && dependencies.HDFS.nameservices?size gt 0>
        <#list dependencies.HDFS.nameservices as ns>
          <#list dependencies.HDFS[ns]['HDFS_NAMENODE'] as namenode>
            <#assign namenodes += [namenode.hostname]>
          </#list>
        </#list>
      <#else>
        <#assign namenodes += dependencies.HDFS.roles.HDFS_NAMENODE[0]['hostname']>
      </#if>
      ${namenodes?join(",")}
  - name: YARN_RESOURCEMANAGER_ADDRRESS
    value: ${service.roles.YARN_RESOURCEMANAGER[0]['hostname']}
  - name: HADOOP_CONF_DIR
    value: /etc/${service.sid}/conf
  mountPath:
  - mountPath: /etc/${service.sid}/conf
    hostPath: /etc/${service.sid}/conf
    name: yarn
  - mountPath: /var/log/${service.sid}
    hostPath: /var/log/${service.sid}
    name: log
  - mountPath: /var/run/hadoop-common
    hostPath: /root/docker/common
    name: socketdir
  - mountPath: /var/transwarp
    hostPath: /var/${service.sid}
    name: transwarp
  - mountPath: /etc/${dependencies.HDFS.sid}/conf
    hostPath: /etc/${dependencies.HDFS.sid}/conf
    name: hdfs
  summaryPolicy: SOME
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [1]}
  suggestion:
  - criteria: !<Range> {"min": 1}
  validation:
  - criteria: !<Range> {"min": 1}
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}/conf", "/var/lock/subsys/${service.sid}", "/var/log/${service.sid}", "/var/run/${service.sid}"]
        mode: "755"
  - type: Config
    directives:
    - directive: !<resource>
        templateType: Raw
        templatePath: "log4j.properties"
        targetPath: "/etc/${service.sid}/conf/log4j.properties"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "yarn-site.ftlx"
        targetPath: "/etc/${service.sid}/conf/yarn-site.xml"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "yarn-env.sh"
        targetPath: "/etc/${service.sid}/conf/yarn-env.sh"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "hadoop-env.sh"
        targetPath: "/etc/${service.sid}/conf/hadoop-env.sh"
        mode: "755"
    - directive: !<link>
        action: Link
        from: "/etc/${dependencies.HDFS.sid}/conf/hdfs-site.xml"
        to: "/etc/${service.sid}/conf/hdfs-site.xml"
    - directive: !<link>
        action: Link
        from: "/etc/${dependencies.HDFS.sid}/conf/core-site.xml"
        to: "/etc/${service.sid}/conf/core-site.xml"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-historyserver.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-historyserver.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-maptask.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-maptask.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-reducetask.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-reducetask.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "yarn.exclude"
        targetPath: "/etc/${service.sid}/conf/yarn.exclude"
        mode: "644"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "mapred-env.sh"
        targetPath: "/etc/${service.sid}/conf/mapred-env.sh"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "mapred-site.ftlx"
        targetPath: "/etc/${service.sid}/conf/mapred-site.xml"
        mode: "755"
    - directive: !<resource>
        templateType: Raw
        templatePath: "taskcontroller.cfg"
        targetPath: "/etc/${service.sid}/conf/taskcontroller.cfg"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "capacity-scheduler.ftlx"
        targetPath: "/etc/${service.sid}/conf/capacity-scheduler.xml"
        mode: "755"
- name: YARN_TIMELINESERVER
  friendlyName: "Timeline Server"
  labelPrefix: "hadoop-yarn-timelineserver"
  category: MASTER
  env:
  - name: USE_EXTERNAL_CONFIG
    value: "true"
  - name: KRB_ENABLE
    value: 'false'
  - name: YARN_TIMELINE_SERVICE_HOSTNAME
    value: ${service.roles.YARN_TIMELINESERVER[0]['hostname']}
  - name: YARN_RESOURCEMANAGER_ADDRRESS
    value: ${service.roles.YARN_RESOURCEMANAGER[0]['hostname']}
  - name: HADOOP_CONF_DIR
    value: /etc/${service.sid}/conf
  - name: HDFS_HA_NAMENODE_SERVICE
    value: |
      <#assign namenodes=[]>
      <#if dependencies.HDFS.nameservices?? && dependencies.HDFS.nameservices?size gt 0>
        <#list dependencies.HDFS.nameservices as ns>
          <#list dependencies.HDFS[ns]['HDFS_NAMENODE'] as namenode>
            <#assign namenodes += [namenode.hostname]>
          </#list>
        </#list>
      <#else>
        <#assign namenodes += dependencies.HDFS.roles.HDFS_NAMENODE[0]['hostname']>
      </#if>
      ${namenodes?join(",")}
  mountPath:
  - mountPath: /etc/${service.sid}/conf
    hostPath: /etc/${service.sid}/conf
    name: yarn
  - mountPath: /var/log/${service.sid}
    hostPath: /var/log/${service.sid}
    name: log
  - mountPath: /var/run/hadoop-common
    hostPath: /root/docker/common
    name: socketdir
  - mountPath: /var/transwarp
    hostPath: /var/${service.sid}
    name: transwarp
  - mountPath: /etc/${dependencies.HDFS.sid}/conf
    hostPath: /etc/${dependencies.HDFS.sid}/conf
    name: hdfs
  summaryPolicy: SOME
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [1]}
  suggestion:
  - criteria: !<Range> {"min": 1}
  validation:
  - criteria: !<Range> {"min": 1}
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}/conf", "/var/lock/subsys/${service.sid}", "/var/log/${service.sid}", "/var/run/${service.sid}"]
        mode: "755"
  - type: Config
    directives:
    - directive: !<resource>
        templateType: Raw
        templatePath: "log4j.properties"
        targetPath: "/etc/${service.sid}/conf/log4j.properties"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "yarn-site.ftlx"
        targetPath: "/etc/${service.sid}/conf/yarn-site.xml"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "yarn-env.sh"
        targetPath: "/etc/${service.sid}/conf/yarn-env.sh"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "hadoop-env.sh"
        targetPath: "/etc/${service.sid}/conf/hadoop-env.sh"
        mode: "755"
    - directive: !<link>
        action: Link
        from: "/etc/${dependencies.HDFS.sid}/conf/hdfs-site.xml"
        to: "/etc/${service.sid}/conf/hdfs-site.xml"
    - directive: !<link>
        action: Link
        from: "/etc/${dependencies.HDFS.sid}/conf/core-site.xml"
        to: "/etc/${service.sid}/conf/core-site.xml"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-maptask.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-maptask.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "hadoop-metrics2-reducetask.properties"
        targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-reducetask.properties"
        mode: "644"
    - directive: !<resource>
        templateType: Raw
        templatePath: "yarn.exclude"
        targetPath: "/etc/${service.sid}/conf/yarn.exclude"
        mode: "644"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "mapred-env.sh"
        targetPath: "/etc/${service.sid}/conf/mapred-env.sh"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "mapred-site.ftlx"
        targetPath: "/etc/${service.sid}/conf/mapred-site.xml"
        mode: "755"
    - directive: !<resource>
        templateType: Raw
        templatePath: "taskcontroller.cfg"
        targetPath: "/etc/${service.sid}/conf/taskcontroller.cfg"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "capacity-scheduler.ftlx"
        targetPath: "/etc/${service.sid}/conf/capacity-scheduler.xml"
        mode: "755"
stages:
  - type: Bootstrap
    taskGroups:
    - !<Create-Dir-in-HDFS>
      summaryPolicy: ALL
      timeoutMinutes: 10
      dirs: ["/tmp" , "/user"]
      user: "hdfs"
      group: "hadoop"
      mod: 777
    - !<Create-Dir-in-HDFS>
      summaryPolicy: ALL
      timeoutMinutes: 10
      dirs: ["/${service.sid}/user" , "/${service.sid}/user/history", "/${service.sid}/var/log/hadoop-yarn/apps"]
      user: "yarn"
      group: "hadoop"
      mod: 777

product: Hadoop

firstWizardConfigs:
- yarn.nodemanager.local-dirs
- yarn.nodemanager.log-dirs
- yarn.nodemanager.remote-app-log-dir
- yarn.app.mapreduce.am.staging-dir
- resourcemanager.admin.port
- resourcemanager.port
- resourcemanager.resource-tracker.port
- resourcemanager.scheduler.port
- resourcemanager.webapp.port
- yarn.nodemanager.resource.cpu-vcores
- yarn.nodemanager.resource.memory-mb
- timelineserver.port
- timelineserver.http.port
- mapred.child.heapsize

dashboardMetrics:
- YarnVCoreUsage
- YarnMemoryUsage

healthChecks:
- category: DAEMON_CHECK
  intervalSeconds: 5
  method: !<K8sPod> {}
