# midas.conf
- name: livy.cache.type
  recommendExpression: "simple"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: livy.scheduler.port
  recommendExpression: 9998
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: livy.storage.basedir
  recommendExpression: "/user/midas"
  defaultValue: null
  valueType: ABSOLUTE_PATH
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: livy.server.port
  recommendExpression: 6066
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
#dieu.conf
- name: dieu.docker.image.name
  recommendExpression: "${dependencies.TOS.roles.TOS_MASTER[0].hostname}:${dependencies.TOS['tos.master.apiserver.port']}/tos/tensorflow:midas-3.1"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: ['TOS']
  groups: []
  visibility: READ_WRITE
- name: dieu.worker.instances
  recommendExpression: 2
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: dieu.ps.instances
  recommendExpression: 2
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: dieu.k8s.namespace
  recommendExpression: "default"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
# midas-env.sh
- name: midas.server.initial_heapsize
  recommendExpression: 512
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: midas.server.heapsize
  recommendExpression: 1024
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: midas.server.permsize
  recommendExpression: 128
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
# spark-defaults.conf
- name: spark.executor.memory
  recommendExpression: 18432
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: spark.driver.memory
  recommendExpression: 18432
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: spark.executor.cores
  recommendExpression: 2
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: spark.executor.instances
  recommendExpression: 4
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: spark.yarn.queue
  recommendExpression: "default"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: spark.sql.warehouse.dir
  recommendExpression: "file:/usr/lib/midas/warehouse"
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
#jvm options for park-default.conf
- name: spark.executor.heapsize
  recommendExpression: 2048
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: spark.executor.permsize
  recommendExpression: 128
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: spark.executor.max_permsize
  recommendExpression: 256
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: spark.driver.heapsize
  recommendExpression: 2048
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: spark.driver.permsize
  recommendExpression: 128
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
- name: spark.driver.max_permsize
  recommendExpression: 256
  defaultValue: null
  valueType: MB
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

# redis
- name: midas.redis.port
  recommendExpression: 6379
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE