<#assign
  registryServer=dependencies.REGISTRY.roles['REGISTRY_SERVER'][0].hostname
  registryPort=dependencies.REGISTRY[registryServer]['registry.port']
  >
<#--handle dependent.zookeeper-->
<#if dependencies.ZOOKEEPER??>
  <#assign zookeeper=dependencies.ZOOKEEPER quorums=[]>
  <#list zookeeper.roles.ZOOKEEPER as role>
    <#assign quorums += [role.hostname]>
  </#list>
  <#assign quorum = quorums?join(",")>
</#if>
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: inceptor-executor-${service.sid}
  name: inceptor-executor-${service.sid}
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: inceptor-executor-${service.sid}
    spec:
      hostNetwork: true 
      containers:
      - args:
        - bootstrap.sh
        - inceptor-executor
        env:
        - name: TRANSWARP_ZOOKEEPER_QUORUM
          value: ${quorum}
        - name: EXECUTOR_ID_PATH
          value: /${service.sid}/executorID
        - name: SPARK_DRIVER_PORT
          value: "51888"
        - name: SPARK_DRIVER_ADDR
          value: ${service.roles.INCEPTOR_SERVER[0]['hostname']}
        - name: SPARK_MEM
          value: 4g
        - name: SPARK_CORES
          value: "1"
        - name: DATADIR
          value: /var/transwarp/data0/
        - name: INCEPTOR_LOG_DIR
          value: /var/transwarp/logs
        - name: SPARK_FASTDISK_DIR
          value: /var/transwarp/data0/fastdisk
        - name: SPARK_LOCAL_DIR
          value: /var/transwarp/data0/disk
        image: ${registryServer}:${registryPort}/jenkins/inceptor:testing-latest
        imagePullPolicy: Always
        name: inceptor-executor-${service.sid}
        # The path mounts on docker
        volumeMounts:
        - mountPath: /var/run/${dependencies.HDFS.sid}
          name: hdfssocketdir
        - mountPath: /var/run/hadoop-common
          name: socketdir
        - mountPath: /etc/inceptor/conf
          name: inceptor
        - mountPath: /etc/hyperbase/conf
          name: hyperbase
        - mountPath: /etc/hadoop/conf
          name: hdfs
        - mountPath: /var/transwarp/logs
          name: log
      # Ensure that a node can have one inceptor-executor at most
      podConflictSelectors:
      - matchExpressions:
        - key: podConflictName
          operator: "="
          values:
          - "inceptor-executor"
      # Ensure that only the node labeled "inceptor-executor" can start a inceptor-executor role (i.e., a pod)
      nodeSelector:
        inceptor-executor: "true"
      # The path on real node
      volumes:
      - hostPath:
          path: /var/run/hdfs
        name: hdfssocketdir
      - hostPath:
          path: /root/docker/common
        name: socketdir
      - hostPath:
          path: /etc/${service.sid}/conf
        name: inceptor
      - hostPath:
          path: /etc/hyperbase1/conf
        name: hyperbase
      - hostPath:
          path: /etc/${dependencies.HDFS.sid}/conf
        name: hdfs
      - hostPath:
          path: /var/log/${service.sid}
        name: log
