<#assign
  registryServer=dependencies.REGISTRY.roles['REGISTRY_SERVER'][0].hostname
  registryPort=dependencies.REGISTRY[registryServer]['registry.port']
  >
apiVersion: v1
kind: Pod # TODO Zookeeper can surport RC ?
metadata:
  labels:
    name: zookeeper-server-${service.sid}-${localhostname}
    podConflictName: zookeeper-server
  name: zookeeper-server-${service.sid}-${localhostname}
  namespace: default
spec:
    containers:
    - args:
      - bootstrap.sh
      - zookeeper
      env:
        - name: USE_EXTERNAL_CONFIG
          value: "true"
        - name: TRANSWARP_DATA_HOME
          value: /var/${service.sid}
        - name: HEAP_SIZE
          value: ${service['zookeeper.server.memory']}m
      image: ${registryServer}:${registryPort}/jenkins/zookeeper
      imagePullPolicy: Always
      name: zookeeper-server-${service.sid}
      # The path mounts on docker
      volumeMounts:
       - mountPath: /var/transwarp/logs
         name: log
       - mountPath: /etc/zookeeper/conf
         name: zookeeper
       - mountPath: /var/${service.sid}
         name: data
    # Ensure that a node can have one zookeeper-server at most
    podConflictSelectors:
    - matchExpressions:
      - key: podConflictName
        operator: "="
        values:
        - "zookeeper-server"
    # Ensure that only the node labeled "zookeeper-server=true" can start a zookeeper role (i.e., a pod)
    nodeSelector:
      zookeeper-server: "true"
    # The path on real node
    volumes:
    - hostPath:
        path: /var/log/${service.sid}
      name: log
    - hostPath:
        path: /etc/${service.sid}/conf
      name: zookeeper
    - hostPath:
        path: /var/${service.sid}
      name: data
    hostNetwork: true
    nodeName: ${localhostname}
