- name: hive.metastore.execute.setugi
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.hwi.war.file
  recommendExpression: lib/hive-hwi-0.8.1.war
  defaultValue: null
  valueType: ABSOLUTE_PATH
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: plsql.compile.dml.check.semantic
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionPassword
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.server2.session.check.interval
  recommendExpression: 60000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.users.in.admin.role
  recommendExpression: hive,hue
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: mapreduce.framework.name
  recommendExpression: yarn
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hbase.client.scanner.caching
  recommendExpression: 500
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: datanucleus.autoStartMechanism
  recommendExpression: SchemaTable
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.input.format
  recommendExpression: org.apache.hadoop.hive.ql.io.HiveInputFormat
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.aux.jars.path
  recommendExpression: file:///usr/lib/hive/lib/hive-hbase-handler.jar,file:///usr/lib/hbase/hbase-bson.jar,file:///usr/lib/hbase/hbase-client.jar,file:///usr/lib/hbase/hbase-common.jar,file:///usr/lib/hbase/hbase-examples.jar,file:///usr/lib/hbase/hbase-hadoop2-compat.jar,file:///usr/lib/hbase/hbase-hadoop-compat.jar,file:///usr/lib/hbase/hbase-hyperbase.jar,file:///usr/lib/hbase/hbase-it.jar,file:///usr/lib/hbase/hbase-prefix-tree.jar,file:///usr/lib/hbase/hbase-protocol.jar,file:///usr/lib/hbase/hbase-server.jar,file:///usr/lib/hbase/hbase-shell.jar,file:///usr/lib/hbase/hbase-testing-util.jar,file:///usr/lib/hbase/hbase-thrift.jar,file:///usr/lib/hbase/chronos-client.jar,file:///usr/lib/hbase/chronos-server.jar,file:///usr/lib/hbase/transaction-client.jar,file:///usr/lib/hbase/transaction-coprocessor.jar,file:///usr/lib/zookeeper/zookeeper.jar,file:///usr/lib/hbase/lib/protobuf-java-2.5.0.jar,file:///usr/lib/hive/lib/kryo-2.21.jar
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.server2.idle.session.timeout
  recommendExpression: 14400000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: datanucleus.fixedDatastore
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionDriverName
  recommendExpression: com.mysql.jdbc.Driver
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: javax.jdo.option.ConnectionUserName
  recommendExpression: hiveuser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.exec.dynamic.partition
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hbase.zookeeper.property.clientPort
  recommendExpression: 2181
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.exec.compress.output
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.server2.authentication
  recommendExpression: NONE
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.server2.idle.operation.timeout
  recommendExpression: 28800000
  defaultValue: null
  valueType: NON_NEG_INT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: datanucleus.autoCreateSchema
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.exec.compress.intermediate
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.server2.logging.operation.enabled
  recommendExpression: false
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: transwarp.docker.network.interfaces
  recommendExpression: eth0
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: transwarp.docker.network.hypervisor-subnetmask
  recommendExpression: 255.255.255.255
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: transwarp.docker.enable
  recommendExpression: true
  defaultValue: null
  valueType: BOOL
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: transwarp.docker.network.policy
  recommendExpression: io.transwarp.docker.DockerNetworkPolicyHostGW
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: [hive_site]
  visibility: READ_WRITE

- name: hive.metastore.password
  recommendExpression: password
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: hive.metastore.username
  recommendExpression: hiveuser
  defaultValue: null
  valueType: STRING
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
