---
name: GUARDIAN
version: 1.0-tdh50
global: true
namePrefix: Guardian
friendlyName: Guardian
dependencies: []
roles:
- name: GUARDIAN_APACHEDS
  friendlyName: "Guardian ApacheDS"
  labelPrefix: "guardian-apacheds"
  category: MASTER
  summaryPolicy: SOME
  dockerImage: "transwarp/apacheds:tdh500"
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [2, 1]}
  suggestion:
  - criteria: !<Range> {"min": 1}
  validation:
  - criteria: !<Range> {"min": 1}
  env: []
  mountPaths:
  - mountPath: /var/lib/guardian-apacheds/data
    hostPath: ${service['guardian.apacheds.data.dir']}
    name: srv
  - mountPath: /etc/guardian-apacheds/conf/persistent
    hostPath: /etc/${service.sid}/conf/
    name: conf
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}/conf", "/${service.sid}/data"]
        mode: "755"
- name: GUARDIAN_SERVER
  friendlyName: "Guardian Server"
  labelPrefix: "guardian-server"
  category: MASTER
  linkExpression: <#if service['guardian.server.tls.enabled'] = "true">https<#else>http</#if>://${localhostname}:${service['guardian.server.port']}
  summaryPolicy: SOME
  dockerImage: "transwarp/guardian:tdh500"
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [2, 1]}
  suggestion:
  - criteria: !<Range> {"min": 1}
  validation:
  - criteria: !<Range> {"min": 1}
  env:
  - name: GUARDIAN_SERVER_KEY_STORE
    value: /srv/guardian/server.keystore
  mountPaths:
  - mountPath: /srv/guardian
    hostPath: /srv/guardian
    name: srv
  - mountPath: /etc/guardian/conf/persistent
    hostPath: /etc/${service.sid}/conf/
    name: conf
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}/conf", "/srv/guardian"]
        mode: "755"
    - directive: !<shell>
        script: "docker run -v /srv/guardian:/srv/guardian --net=host ${dependencies.TOS.roles['TOS_REGISTRY'][0].hostname}:${dependencies.TOS['tos.registry.port']}/transwarp/guardian-gencerts:tdh500 entry.sh"

jobs:
  - type: Init
    stages:
    - Install
    - Config
    - Start
    - GenKeytab
  - type: Start
    stages:
    - Start
    - GenKeytab

firstWizardConfigs:
- guardian.server.port
- guardian.apacheds.ldap.port
- guardian.apacheds.kdc.port
- guardian.apacheds.data.dir

principals:
- guardian/guardian

healthChecks:
- category: DAEMON_CHECK
  intervalSeconds: 15
  method: !<K8sPod> {}
