<#assign
  registryServer=dependencies.REGISTRY.roles['REGISTRY_SERVER'][0].hostname
  registryPort=dependencies.REGISTRY[registryServer]['registry.port']
  >
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: hyperbase-regionserver-${service.sid}
  name: hyperbase-regionserver-${service.sid}
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: hyperbase-regionserver-${service.sid}
        podConflictName: hyperbase-regionserver
    spec:
      hostNetwork: true 
      containers:
      - args:
        - bootstrap.sh
        - regionserver
        env:
        - name: HEAP_SIZE
          value: 4096m
        image: ${registryServer}:${registryPort}/jenkins/hbase
        imagePullPolicy: Always
        name: hyperbase-regionserver-${service.sid}
        volumeMounts:
        - mountPath: /etc/hyperbase/conf
          name: hyperbase
        - mountPath: /etc/hadoop/conf
          name: hdfs
        - mountPath: /var/run/hadoop-common
          name: socketdir
        - mountPath: /var/transwarp/logs
          name: log
      # Ensure that a node can have one hyperbase-regionserver at most
      podConflictSelectors:
      - matchExpressions:
        - key: podConflictName
          operator: "="
          values:
          - "hyperbase-regionserver"
      # Ensure that only the node labeled "hyperbase-regionserver=true" can start a hyperbase-regionserver role (i.e., a pod)
      nodeSelector:
        hyperbase-regionserver: "true"
      # The path on real node
      volumes:
      - hostPath:
          path: /var/log/${service.sid}
        name: log
      - hostPath:
          path: /etc/${service.sid}/conf
        name: hyperbase
      - hostPath:
          path: /etc/${dependencies.HDFS.sid}/conf
        name: hdfs
      - hostPath:
          path: /root/docker/common
        name: socketdir
