<#assign
  registryServer=dependencies.REGISTRY.roles['REGISTRY_SERVER'][0].hostname
  registryPort=dependencies.REGISTRY['registry.port']
  >
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: inceptor-mysql-${service.sid}
  name: inceptor-mysql-${service.sid}
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: inceptor-mysql-${service.sid}
        podConflictName: inceptor-mysql-${service.sid}
    spec:
      hostNetwork: true
      containers:
      - args:
        - bootstrap.sh
        - mysql
        env:
        - name: METASTORE_ID
          value: metastore_${service.sid}
        - name: JAVAX_JDO_OPTION_CONNECTIONURL
          value: jdbc:mysql://0.0.0.0:3306/metastore_${service.sid}
        - name: JAVAX_JDO_OPTION_CONNECTION_USERNAME
          value: ${service['hive.metastore.username']}
        - name: JAVAX_JDO_OPTION_CONNECTION_PASSWORD
          value: ${service['hive.metastore.password']}
        image: ${registryServer}:${registryPort}/jenkins/inceptor:testing-latest
        imagePullPolicy: Always
        name: inceptor-mysql-${service.sid}
        # The path mounts on docker
        volumeMounts:
        - mountPath: /var/transwarp
          name: mysql
      # Ensure that a node can have one inceptor-mysql at most
      podConflictSelectors:
      - matchExpressions:
        - key: podConflictName
          operator: "="
          values:
          - "inceptor-mysql-${service.sid}"
      # Ensure that only the node labeled "inceptor-mysql=true" can start a inceptor-mysql role (i.e., a pod)
      nodeSelector:
        inceptor-mysql-${service.sid}: "true"
      # The path on real node
      volumes:
      - hostPath:
          path: /var/lib/mysql
        name: mysql
