---
name: HDFS
version: 2.5.2-tdh50
global: false
namePrefix: HDFS
friendlyName: HDFS
user: hdfs
dependencies:
#  - name: LICENSE_SERVICE
#    minVersion: 1.0
#    maxVersion: 1.0
#    optional: false
  - name: ZOOKEEPER
    minVersion: 3.4.5-tdh50
    maxVersion: 3.4.5-tdh50
    optional: false
roles:
  - name: HDFS_DATANODE
    friendlyName: "Data Node"
    summaryPolicy: SOME
    autoAssign:
      - advice: !<EachNode> {}
    suggestion:
      - criteria: !<Range>
          min: 3
    validation:
      - criteria: !<Range>
          min: 1
    operations:
    - type: Install
      directives:
      - directive: !<mkdirs>
          paths: ["/etc/${service.sid}", "/etc/${service.sid}/conf", "/var/${service.sid}", "/var/log/${service.sid}"]
          mode: "755"
    - type: Config
      directives:
      - directive: !<resource>
          templateType: Raw
          templatePath: "log4j.properties"
          targetPath: "/etc/${service.sid}/conf/log4j.properties"
          mode: "755"
      - directive: !<resource>
          templateType: Raw
          templatePath: "hadoop-metrics2-datanode.properties"
          targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-datanode.properties"
          mode: "755"
      - directive: !<resource>
          templateType: Raw
          templatePath: "hadoop-metrics2-namenode.properties"
          targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-namenode.properties"
          mode: "755"
      - directive: !<resource>
            templateType: FreeMarker
            templatePath: "core-site.ftlx"
            targetPath: "/etc/${service.sid}/conf/core-site.xml"
            mode: "755"
      - directive: !<resource>
            templateType: FreeMarker
            templatePath: "hdfs-site.ftlx"
            targetPath: "/etc/${service.sid}/conf/hdfs-site.xml"
            mode: "755"
      - directive: !<resource>
          templateType: FreeMarker
          templatePath: "hadoop-env.sh"
          targetPath: "/etc/${service.sid}/conf/hadoop-env.sh"
          mode: "755"
      - directive: !<resource>
            templateType: FreeMarker
            templatePath: "hdfs-datanode.yaml"
            targetPath: "/etc/${service.sid}/hadoop-hdfs-datanode-${service.sid}.yaml"
            mode: "755"
#    - type: Start
#      directives:
#      # Add labelKey "hdfs-datanode" for node ${localhostname}
#      - directive: !<kubectl-label>
#            action: AddLabel
#            hostname: ${localhostname}
#            labelKey: "hdfs-datanode"
#      - directive: !<kubectl>
#            action: Start
#            file: "/etc/${service.sid}/hadoop-hdfs-datanode-${service.sid}.yaml"
#    - type: Stop
#      directives:
#      - directive: !<kubectl>
#            action: Stop
#            file: "/etc/${service.sid}/hadoop-hdfs-datanode-${service.sid}.yaml"
  - name: HDFS_NAMENODE
    friendlyName: "Name Node (non-HA)"
    summaryPolicy: SOME
    autoAssign: []
    suggestion:
      - criteria: !<Range>
          min: 0
          max: 0
    validation:
      - when: !<WhenRoleGroup>
          fieldName: nameservices
          inRange: {"min": 0, "max": 0}
        criteria: !<Range>
          min: 1
          max: 1
      - when: !<WhenRoleGroup>
          fieldName: nameservices
          inRange: {"min": 1}
        criteria: !<Range>
          min: 0,
          max: 0
    operations:
      - type: Install
        directives:
        - directive: !<mkdirs>
            paths: ["/etc/${service.sid}", "/etc/${service.sid}/conf", "/var/${service.sid}", "/var/log/${service.sid}"]
            mode: "755"
      - type: Config
        directives:
        - directive: !<resource>
            templateType: Raw
            templatePath: "log4j.properties"
            targetPath: "/etc/${service.sid}/conf/log4j.properties"
            mode: "755"
        - directive: !<resource>
            templateType: Raw
            templatePath: "hadoop-metrics2-datanode.properties"
            targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-datanode.properties"
            mode: "755"
        - directive: !<resource>
            templateType: Raw
            templatePath: "hadoop-metrics2-namenode.properties"
            targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-namenode.properties"
            mode: "755"
        - directive: !<resource>
            templateType: FreeMarker
            templatePath: "core-site.ftlx"
            targetPath: "/etc/${service.sid}/conf/core-site.xml"
            mode: "755"
        - directive: !<resource>
            templateType: FreeMarker
            templatePath: "hdfs-site.ftlx"
            targetPath: "/etc/${service.sid}/conf/hdfs-site.xml"
            mode: "755"
        - directive: !<resource>
            templateType: FreeMarker
            templatePath: "exclude-list.txt"
            targetPath: "/etc/${service.sid}/conf/exclude-list.txt"
            mode: "755"
        - directive: !<resource>
            templateType: FreeMarker
            templatePath: "hadoop-env.sh"
            targetPath: "/etc/${service.sid}/conf/hadoop-env.sh"
            mode: "755"
        - directive: !<resource>
            templateType: FreeMarker
            templatePath: "hdfs-namenode.yaml"
            targetPath: "/etc/${service.sid}/hadoop-hdfs-namenode-${service.sid}.yaml"
            mode: "755"
#      - type: Start
#        directives:
#        # Add labelKey "hdfs-namenode" for node ${localhostname}
#        - directive: !<kubectl-label>
#            action: AddLabel
#            hostname: ${localhostname}
#            labelKey: "hdfs-namenode"
#        - directive: !<kubectl>
#            action: Start
#            file: "/etc/${service.sid}/hadoop-hdfs-namenode-${service.sid}.yaml"
#      - type: Stop
#        directives:
#        - directive: !<kubectl>
#            action: Stop
#            file: "/etc/${service.sid}/hadoop-hdfs-namenode-${service.sid}.yaml"
roleGroups:
  - fieldName: nameservices
    namePrefix: nameservice
    friendlyName: "Name Service"
    autoAssign:
      - advice: !<NumSeq> {"numSeq": [1]}
    suggestion:
      - criteria: !<Range> {"min": 1}
    validation:
      - when: !<WhenRoleType>
          roleType: HDFS_NAMENODE
          inRange: {"min": 0, "max": 0}
        criteria: !<Range> {"min": 1}
      - when: !<WhenRoleType>
          roleType: HDFS_NAMENODE
          inRange: {"min": 1}
        criteria: !<Range>
          min: 0
          max: 0
    roles:
      - name: HDFS_NAMENODE
        friendlyName: "Name Node"
        summaryPolicy: ALL
        autoAssign:
          - advice: !<NumSeq>
              numSeq: [2, 1]
              mates: ["LICENSE_NODE"]
        suggestion:
          - criteria: !<Range> {"min": 2, "max": 2}
        validation:
          - criteria: !<Range> {"min": 1, "max": 2}
        operations:
          - type: Install
            directives:
            - directive: !<mkdirs>
                paths: ["/etc/${service.sid}", "/etc/${service.sid}/conf", "/var/${service.sid}", "/var/log/${service.sid}"]
                mode: "755"
          - type: Config
            directives:
            - directive: !<resource>
                templateType: Raw
                templatePath: "log4j.properties"
                targetPath: "/etc/${service.sid}/conf/log4j.properties"
                mode: "755"
            - directive: !<resource>
                templateType: Raw
                templatePath: "hadoop-metrics2-datanode.properties"
                targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-datanode.properties"
                mode: "755"
            - directive: !<resource>
                templateType: Raw
                templatePath: "hadoop-metrics2-namenode.properties"
                targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-namenode.properties"
                mode: "755"
            - directive: !<resource>
                templateType: FreeMarker
                templatePath: "core-site.ftlx"
                targetPath: "/etc/${service.sid}/conf/core-site.xml"
                mode: "755"
            - directive: !<resource>
                templateType: FreeMarker
                templatePath: "hdfs-site.ftlx"
                targetPath: "/etc/${service.sid}/conf/hdfs-site.xml"
                mode: "755"
            - directive: !<resource>
                templateType: FreeMarker
                templatePath: "exclude-list.txt"
                targetPath: "/etc/${service.sid}/conf/exclude-list.txt"
                mode: "755"
            - directive: !<resource>
                templateType: FreeMarker
                templatePath: "hadoop-env.sh"
                targetPath: "/etc/${service.sid}/conf/hadoop-env.sh"
                mode: "755"
            - directive: !<resource>
                templateType: FreeMarker
                templatePath: "hdfs-namenode.yaml"
                targetPath: "/etc/${service.sid}/hadoop-hdfs-namenode-${service.sid}.yaml"
                mode: "755"
#          - type: Start
#            directives:
#            # Add labelKey "hdfs-namenode" for node ${localhostname}
#            - directive: !<kubectl-label>
#                action: AddLabel
#                hostname: ${localhostname}
#                labelKey: "hdfs-namenode"
#            - directive: !<kubectl>
#                action: Start
#                file: "/etc/${service.sid}/hadoop-hdfs-namenode-${service.sid}.yaml"
#          - type: Stop
#            directives:
#            - directive: !<kubectl>
#                action: Stop
#                file: "/etc/${service.sid}/hadoop-hdfs-namenode-${service.sid}.yaml"
      - name: HDFS_JOURNALNODE
        friendlyName: "Journal Node"
        summaryPolicy: MAJOR
        autoAssign:
          - when: !<WhenRoleType>
              roleType: HDFS_NAMENODE
              inRange: {"min": 2}
            advice: !<NumSeq>
              numSeq: [3, 1]
              mates: ["HDFS_NAMENODE"]
        suggestion:
          - when: !<WhenRoleType>
              roleType: HDFS_NAMENODE
              inRange: {"min": 2}
            criteria: !<Range>
              min: 3
              oddity: true
        validation:
          - when: !<WhenRoleType>
              roleType: HDFS_NAMENODE
              inRange: {"min": 1, "max": 1}
            criteria: !<Range>
              min: 0
              max: 0
          - when: !<WhenRoleType>
              roleType: HDFS_NAMENODE
              inRange: {"min": 2}
            criteria: !<Range> {"min": 1}
        operations:
          - type: Install
            directives:
            - directive: !<mkdirs>
                paths: ["/etc/${service.sid}", "/etc/${service.sid}/conf", "/var/${service.sid}", "/var/log/${service.sid}"]
                mode: "755"
          - type: Config
            directives:
            - directive: !<resource>
                templateType: Raw
                templatePath: "log4j.properties"
                targetPath: "/etc/${service.sid}/conf/log4j.properties"
                mode: "755"
            - directive: !<resource>
                templateType: Raw
                templatePath: "hadoop-metrics2-datanode.properties"
                targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-datanode.properties"
                mode: "755"
            - directive: !<resource>
                templateType: Raw
                templatePath: "hadoop-metrics2-namenode.properties"
                targetPath: "/etc/${service.sid}/conf/hadoop-metrics2-namenode.properties"
                mode: "755"
            - directive: !<resource>
                templateType: FreeMarker
                templatePath: "core-site.ftlx"
                targetPath: "/etc/${service.sid}/conf/core-site.xml"
                mode: "755"
            - directive: !<resource>
                templateType: FreeMarker
                templatePath: "hdfs-site.ftlx"
                targetPath: "/etc/${service.sid}/conf/hdfs-site.xml"
                mode: "755"
            - directive: !<resource>
                templateType: FreeMarker
                templatePath: "hdfs-journalnode.yaml"
                targetPath: "/etc/${service.sid}/hadoop-hdfs-journalnode-${service.sid}.yaml"
                mode: "755"
#          - type: Start
#            directives:
#            # Add labelKey "hdfs-journalnode" for node ${localhostname}
#            - directive: !<kubectl-label>
#                action: AddLabel
#                hostname: ${localhostname}
#                labelKey: "hdfs-journalnode"
#            - directive: !<kubectl>
#                action: Start
#                file: "/etc/${service.sid}/hadoop-hdfs-journalnode-${service.sid}.yaml"
#          - type: Stop
#            directives:
#            - directive: !<kubectl>
#                action: Stop
#                file: "/etc/${service.sid}/hadoop-hdfs-journalnode-${service.sid}.yaml"
stages:
  - type: Start
    taskGroups:
    - !<Kubectl-Label>
      summaryPolicy: SOME
      timeoutMinutes: 2
      roleType: HDFS_DATANODE
      action: AddLabel
      labelKey: "hdfs-datanode"
      labelValue: "true"
    - !<Kubectl>
      summaryPolicy: MAJOR
      timeoutMinutes: 2
      roleType: HDFS_DATANODE
      action: Start
      file: "hdfs-datanode.yaml"
    - !<Kubectl-Label>
      summaryPolicy: SOME
      timeoutMinutes: 2
      roleType: HDFS_JOURNALNODE
      action: AddLabel
      labelKey: "hdfs-journalnode"
      labelValue: "true"
    - !<Kubectl>
      summaryPolicy: MAJOR
      timeoutMinutes: 2
      roleType: HDFS_JOURNALNODE
      action: Start
      file: "hdfs-journalnode.yaml"
    - !<Kubectl-Label>
      summaryPolicy: SOME
      timeoutMinutes: 2
      roleType: HDFS_NAMENODE
      action: AddLabel
      labelKey: "hdfs-namenode"
      labelValue: "true"
    - !<Kubectl>
      summaryPolicy: MAJOR
      timeoutMinutes: 2
      roleType: HDFS_NAMENODE
      action: Start
      file: "hdfs-namenode1.yaml"
    - !<Kubectl>
      summaryPolicy: MAJOR
      timeoutMinutes: 2
      roleType: HDFS_NAMENODE
      action: Start
      file: "hdfs-namenode2.yaml"
  - type: Stop
    taskGroups:
    - !<Kubectl-Label>
      summaryPolicy: SOME
      timeoutMinutes: 2
      roleType: HDFS_DATANODE
      action: RemoveLabel
      labelKey: "hdfs-datanode"
      labelValue: "true"
    - !<Kubectl>
      summaryPolicy: MAJOR
      timeoutMinutes: 2
      roleType: HDFS_DATANODE
      action: Stop
      file: "hdfs-datanode.yaml"
    - !<Kubectl-Label>
      summaryPolicy: SOME
      timeoutMinutes: 2
      roleType: HDFS_JOURNALNODE
      action: RemoveLabel
      labelKey: "hdfs-journalnode"
      labelValue: "true"
    - !<Kubectl>
      summaryPolicy: MAJOR
      timeoutMinutes: 2
      roleType: HDFS_JOURNALNODE
      action: Stop
      file: "hdfs-journalnode.yaml"
    - !<Kubectl-Label>
      summaryPolicy: SOME
      timeoutMinutes: 2
      roleType: HDFS_NAMENODE
      action: RemoveLabel
      labelKey: "hdfs-namenode"
      labelValue: "true"
    - !<Kubectl>
      summaryPolicy: MAJOR
      timeoutMinutes: 2
      roleType: HDFS_NAMENODE
      action: Stop
      file: "hdfs-namenode1.yaml"
    - !<Kubectl>
      summaryPolicy: MAJOR
      timeoutMinutes: 2
      roleType: HDFS_NAMENODE
      action: Stop
      file: "hdfs-namenode2.yaml"
