---
name: LICENSE_SERVICE
version: 1.0
global: true
# compatible with legacy init.d script name "zookeeper-server-transwarp_license_cluster"
namePrefix: Transwarp_License_Cluster
friendlyName: "License Service"
dependencies: []
user: zookeeper
roles:
- name: LICENSE_NODE
  friendlyName: "License Node"
  # compatible with legacy init.d script name "zookeeper-server-transwarp_license_cluster"
  labelPrefix: "zookeeper-server"
  summaryPolicy: MAJOR
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [5, 3, 1]}
  suggestion:
  - criteria: !<Range> {"min": 3, "oddity": true}
  validation:
  - criteria: !<Range> {"min": 1}
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}", "/etc/${service.sid}/conf", "/var/${service.sid}", "/var/run/${service.sid}", "/var/log/${service.sid}"]
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "zookeeper-server.ftlsh"
        targetPath: "/etc/init.d/zookeeper-server-${service.sid}"
        mode: "755"
        owner: "root"
        group: "root"
  - type: Config
    directives:
    - directive: !<resource>
        templateType: Raw
        templatePath: "log4j.properties"
        targetPath: "/etc/${service.sid}/conf/log4j.properties"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "zoo-env.sh"
        targetPath: "/etc/${service.sid}/conf/zoo-env.sh"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "zoo_conf.ftlp"
        targetPath: "/etc/${service.sid}/conf/zoo.cfg"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "myid"
        targetPath: "/var/${service.sid}/myid"
        mode: "755"
stages:
  - type: Start
    taskGroups:
    - !<Role>
      summaryPolicy: SOME
      timeoutMinutes: 10
      roleType: LICENSE_NODE
      operation: Start
    - !<Upload-License>
      summaryPolicy: ALL
      timeoutMinutes: 10
