---
name: LICENSE_SERVICE
version: 1.0
global: true
namePrefix: LicenseService
friendlyName: "License Service"
dependencies: []
user: zookeeper
roles:
- name: LICENSE_NODE
  friendlyName: "License Node"
  summaryPolicy: MAJOR
  autoAssign:
  - advice: !<NumSeq> {"numSeq": [5, 3, 1]}
  suggestion:
  - criteria: !<Range> {"min": 3, "oddity": true}
  validation:
  - criteria: !<Range> {"min": 1}
  operations:
  - type: Install
    directives:
    - directive: !<mkdirs>
        paths: ["/etc/${service.sid}", "/etc/${service.sid}/conf", "/var/${service.sid}", "/var/run/${service.sid}", "/var/log/${service.sid}"]
        mode: "755"
  - type: Config
    directives:
    - directive: !<resource>
        templateType: Raw
        templatePath: "log4j.properties"
        targetPath: "/etc/${service.sid}/conf/log4j.properties"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "zoo-env.sh"
        targetPath: "/etc/${service.sid}/conf/zoo-env.sh"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "zoo_conf.ftlp"
        targetPath: "/etc/${service.sid}/conf/zoo.cfg"
        mode: "755"
    - directive: !<resource>
        templateType: FreeMarker
        templatePath: "myid"
        targetPath: "/var/${service.sid}/myid"
        mode: "755"
#    - directive: !<resource>
#        templateType: FreeMarker
#        templatePath: "zookeeper.yaml"
#        targetPath: "/etc/${service.sid}/zookeeper-server-${service.sid}.yaml"
#        mode: "755"
#  - type: Start
#    directives:
#    # Add labelKey "zookeeper-server" for node ${localhostname}
#    - directive: !<kubectl-label>
#        action: AddLabel
#        hostname: ${localhostname}
#        labelKey: "zookeeper-server"
#    # Start zookeeper using zookeeper-server-${service.sid}.yaml
#    - directive: !<kubectl>
#        action: Start
#        file: "/etc/${service.sid}/zookeeper-server-${service.sid}.yaml"
#  - type: Stop
#    directives:
#    - directive: !<kubectl>
#        action: Stop
#        file: "/etc/${service.sid}/zookeeper-server-${service.sid}.yaml"
stages:
  - type: Start
    taskGroups:
    - !<Kubectl-Label>
      summaryPolicy: SOME
      timeoutMinutes: 2
      roleType: LICENSE_NODE
      action: AddLabel
      labelKey: "license-node"
      labelValue: "true"
    - !<Kubectl>
      summaryPolicy: MAJOR
      timeoutMinutes: 2
      action: Start
      file: "zookeeper.yaml"
    - !<Upload-License>
      summaryPolicy: ALL
      timeoutMinutes: 10
  - type: Stop
    taskGroups:
    - !<Kubectl-Label>
      summaryPolicy: SOME
      timeoutMinutes: 2
      roleType: LICENSE_NODE
      action: RemoveLabel
      labelKey: "license-node"
      labelValue: "true"
    - !<Kubectl>
      summaryPolicy: MAJOR
      timeoutMinutes: 2
      action: Stop
      file: "zookeeper.yaml"
