---
- name: tos.master.etcd.port
  recommendExpression: 4001
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TOS_MASTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE
# for tos ha
- name: tos.master.leader.elect.port
  recommendExpression: 4002
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TOS_MASTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tos.master.apiserver.port
  recommendExpression: 8080
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TOS_MASTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tos.master.apiserver.secure.port
  recommendExpression: 8443
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TOS_MASTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tos.master.scheduler.port
  recommendExpression: 10251
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TOS_MASTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tos.master.controller.port
  recommendExpression: 10252
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TOS_MASTER]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tos.slave.kubelet.port
  recommendExpression: 10250
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TOS_SLAVE]
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tos.slave.kubelet.healthzport
  recommendExpression: 10248
  defaultValue: null
  valueType: PORT
  scope: !<RoleTypes>
    roleTypes: [TOS_SLAVE]
  onDeps: []
  groups: []
  visibility: READ_WRITE
# TODO tos.haproxy.port

- name: tos.master.dashboard.username
  recommendExpression: dashboard
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE

- name: tos.master.dashboard.password
  recommendExpression: password
  defaultValue: null
  valueType: PORT
  scope: !<ServiceLevel> {}
  onDeps: []
  groups: []
  visibility: READ_WRITE
